### ISSUE TITLE
Cheers!

### ISSUE THREAD

**Issue by dderiso** [cdcme/hippy#1]
Hi Carlo,

Thanks for making this public. I am studying your approach and wanted to know if you would recommend a stack like this?  I'm building a course website and contemplating Flask, Sinatra, and Node for their simplicity. What else did you try?

Cheers,
Dave

**Comment by cdcme** [comment]
Hi, Dave!

Without knowing a lot about what you want to do, I would suggest node. The purpose of the hippy stack was to try to create a node-like stack in python in order to come up with a more performant API framework while working within some technology constraints at my job. However, I wouldn’t recommend this for new projects if you don’t already have technology constraints.  

It sounds like you are trying to build a SaaS educational platform. If that’s the case, I would recommend node above anything else out there right now. If you’re looking for a good framework, I would recommend either Meteor or Sails - both of which I know from personal experience will give you great, consistent APIs to work with that are built on top of node, so you can dive down into node itself any time you need or want to but won’t be slowed down by having to do every little thing yourself.  

I guess in my personal experience, the most important thing is to select a set of technologies that won’t be obstacles to finishing what you set out to do. In other words, try to make the completion of your app as attainable a goal as possible. I feel like node will definitely help you do that better than most stacks.  

Hope this helps & good luck with your project!

Carlo DiCelico

**Comment by dderiso** [comment]
Hi Carlo,

Thanks for the reply! I was leaning towards python because there's some math I want to do on the back end in numpy and I wanted to make a minimalist API wrapper in the same language. However, "make the completion of your app as attainable a goal as possible" is sound advice and I agree that Node is more in line with this philosophy. Thanks for chiming in and thanks again for posting your code.

Cheers,
Dave

**Comment by cdcme** [comment]
No problemo! I'd also chime in that it's perfectly okay to have separate operations and data stacks. Typically, you'd do something like this:
1. generate data from your web app (operations)
2. store that in a database somewhere (operations)
3. gather/clean that data (and potentially data from other sources) and move it into a data warehouse (ETL) (data)
4. analysis & reporting on the backend (data)

So, 1 and 2 could be in node and everything else could be in python if you wanted to do that. Separating these out means maintaining different codebases, true, but it also allows you to keep the two sides of your operation cleanly separated and to use the best tool for the job - node for web stuff and python for data.
